env:
  global:
   - secure: Qu5dqjC/SBegoTLZdhCwqMznPULxcR0/NMNmFMPckvoaoxwbOQqLO6TuiuR88KeHHAJ0ZXeT8aUyQVmhA0KT6OF6v4TcdSfkO/1z+fx+Dc+Kybm3ZQ9AJ+t0ANGcOtUGke51QYXJiTJPUMCDCQ5usfgf4AILXfDX9NoQDYeP+j6bI4vB5er5vf6M3c0A9FfpE48letm2Ux3Jb0Vr1VIivbT4pnfdifDBJs7KrK+5KxA/FSbigZjUrTqorNys/puWL3mCBt6Y3kImkJUTlwd0pEXTammLwEnckiSeme6zUfuCyVQ5BS37DJB2Puiq9rRPR7lauk4lCseFTns9Gp/1dRRy0VLT7HJIG13cDaXokHaRwhZLvLrfahNAuETIyx5VlmnnAuFbrhcKAmGPluaWs18VPrSq1K1jWloMaxcSOUOoGuJ91r5sumqL3CkrOauO3MnGwNxPlZ5b9HK4kjhXZDmzupCzeirrqAh3DJIeZ3EiXjsXY6MehRX/ZiWrBouiTE/tL/3ZrpimbhM1mQdA/dGoCNLdcFmn94LXdXkzYdfG8oztUdr+8RxJqzsfby+duS/7IChBfcVy7H8n2ATyT5hEZZsd46cgonG/G3EoezSKZUYaO53f1iuIBJTwqXcnhufuUTxxNUmKWwJP67/SEusRXEKtCB6OIEnXkaFu0ZA=
   - secure: kWpUjW6x+fdLUS7MWBYFfaNn8Y7a8Q06olrYcnJr35sNv9CWqnjn37hwzuLLdSNIyVvkRkAa3CuIUOSfPrSLODcP+2Bbark1P7LMUZbIspD2visthYzZJkELAqwkubgL+phy0ey/QTOdgFXjzfPjnushCiI1NXQfrf258VUohw5x9K8dJoP5K5DJJnD2elAt2Dfq8d+FpwGYtF2NBSDoTmXo5nleqnfoyAq2V1J4P7kH4sUAtkg1fTDOY1PVe82EfeYcR9XrYyXhw6X8iQ7Flv9Ckb5vS8RnyhZvBzvnFWgX850GnAUFpQFtAQHiWyBU3WK4zjQOq/w5YtBSjgrROxtiOuanpYDYiN3KZKrwo27xlfSTvuNhgPQPaYAqMIAnIyq4sRhco2wUkE3vv83mzXkhEkcgDZC24boVrL1VdjCNxD0DlReoXMts8jeE+bz6qy4WE/sRIhFgX2o38A1i+5Ormoinslgld5eLBv6OTCu+WYoHhU4c1/XwPUmbzc1uwkzalwjVw573rpUsTgQzBC3LgHp8I6V+ZIEZa3iterlD1LCfvlCbP2tDk8ET3r30BH9dMgpxOWtq/+T8g14ZILAWHj6GaervFR8wjbJkPxmAAZAT/DthRd4TABALNgijh66ByN2d+daRUrkEkH6eoP20eLDy3ueXJ7EVOx6/XtU=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantique
    token:
      secure: L5S22/CGHl3QfKBkp0DXvhYySCXHsnWF5drwFlMoGYtQihto3UmZF+muEf6KSs2BkNAmJ7rABsTjJL7x8+t9QdPefhm7Gn/QkrdC6kEZzG3Hk7NkVOSkGKkYMeqHrLo/WNM5Gdq16qPFDKyjGXfqgET1n/YwOtWYttSM15mKMMbpXiDnHaTdNunDC8how0Bc8VvRdr8bcsoIjvzgg9cgeqwIPG1rtnEOjjNbvZKJ4Yj8cLNs/azxZFDW/jm/jk5b82TaiDcWMFZmLIy7C8pDlUi2fNlFO+MyT652q+7Y7XHxtRRuVFo2AvE4yxIBPr4Kjad5FgENz/C/FTqm9z444vQQ6YS1+zA85dIgJuoM24dEy0ooxYMD3wmBRvxOns6OkIkHv6WFYLz8K6eivLbfHkEbWxkLytNYcaGB+BxgK5sro9c2m4F/Xk7zySLKgrfVpMPieSch53Sk9fUVesW5D0N/M51mSIULyXNzuMQGyenC9WZ4LNesPOfhkqFZuci2vUuNX8ulwnlvxwqv2fDt+yFMJ1+q9m7lUD5uUYU0u3CyFL+jq2H9KnLhUjp2woCEV03Xwd2qtR1Aj5ZdQjcy0+eYSslm1iIUW5YlRa0fRanxNFqlcide0Oc3IHrq3sQxsEmp/Ufl5BVYY/7luNw29E1BIJuxt6I6WiE0pDqw4RE=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull julienbayle/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t julienbayle/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: p+MqEryobJfeuJop9BizDj/2H5duqL3GtADxcSDFcNegy7D7rRFAZjR9q5l+EeQH5m7ieLLLCxuj91dRfengxq+JI+xBn1j3fpyEXHC3ZJDVSksI/xg0xkU/6D/QEm8GlnOf2rqb9ZwcJekZRJl8AnMZhbBfxKxxxPqyd3Dpo8+3sKtw8B+So5F04h0+poIVsuLXMESqoaj006w7PBEjWpFzCEhZMzVykSYXDjRON9XnVKN5XRNK2ygCTI1z1v/5tzoxeuxwv+qOfd/mrULj4k0qLa+T72aRFxl5PW/yHYohDhqhoTClV99BiyNzACGd0eRAPFNt8PiYqm38ZhoRXq/u/sESykTX76LwryXMEpNHzd2yUOIyVmG6MIaGs8kmQq6M3Vuce4h/YdxxhYYCp9491v0cPjQ+BWBtsWaB0HYnMrwgi6IkHw41DwefINENbF9wMNSUJ/6qU471nUiWLcjj1tguC8zR97FlKvSrqEQuXk9wC2yrOiKG54zFgh+kKn1a0Gkf1FhLZZczlE63b+j73h1m7VzHa/wb6Q1/++pmYsCNjXIaVM3KFstXieMclitfvs+DHvYUXr1SYFhSP//62pP37yT0ox1gxzUmlqbOv5SZEV42sQEUXRf8OVbk3+hVCOnFkdi8PcTVybwR4GC2wjjS9XX9wM4bShQbA34=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
